name: final_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 1.0.0
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  crypto: ^3.0.0
  cached_network_image: ^3.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/birds/
    - assets/images/cats/
    - assets/images/developers/
    - assets/images/dogs/
    - assets/images/icons/
    - assets/images/rabbits/
    - assets/json/developers.json
    - assets/json/pets.json

  fonts:
    - family: Siemreap
      fonts:
        - asset: assets/fonts/kh/Siemreap.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/en/SourceSansPro-Regular.ttf
        - asset: assets/fonts/en/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/en/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/en/SourceSansPro-Italic.ttf
          weight: 500
        - asset: assets/fonts/en/SourceSansPro-Light.ttf
          weight: 300
